version: '3.8'

services:
  scraper_app: # Serviço para rodar o scraper (execução única)
    build: .
    env_file:
      - .env
    restart: "no" # O scraper deve rodar e parar, não reiniciar automaticamente
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    # Para rodar o scraper manualmente de dentro do container, pode usar:
    # command: ["python", "-m", "src.main"] 

  web_interface: # Serviço para a interface web (rodando continuamente)
    build: . # Usa a mesma imagem do Dockerfile
    env_file:
      - .env # Precisa das mesmas credenciais do DB
    ports:
      - "5000:5000" # Mapeia a porta 5000 do container para a porta 5000 do host
    restart: unless-stopped # Tenta reiniciar se o container parar inesperadamente
    volumes:
      - ./src:/app/src # Mapeia o código fonte para desenvolvimento
      - ./logs:/app/logs
      - ./data:/app/data
    environment: # Define variáveis de ambiente para o container
      FLASK_APP: src.app_web # INFORMA AO FLASK ONDE ESTÁ SEU ARQUIVO DE APP
      FLASK_ENV: development # <-- NOVO: Define o ambiente Flask para desenvolvimento
      FLASK_DEBUG: 1         # <-- NOVO: Ativa o modo debug do Flask
    command: ["flask", "run", "--host", "0.0.0.0"] # Comando para iniciar o Flask aqui